### ISSUE TITLE
Please add option to rename currencies on player sheet

### ISSUE THREAD

**Issue by ian-aus** [Xander-Carroll/xanders-swnr-sheet#1]
Hi. Great sheets, thank you. Winter's default SWNR sheets allow for renaming of the currencies on player sheets via the sheet tweeks button. Would it be possible to add this to your sheets?

**Comment by Xander-Carroll** [comment]
I released a quick update which should let you rename currencies when the sheet is unlocked. 

The fields are pretty small, so I may restyle the sheet in the future to support bigger currency names. I have created a to-do item for that [here](https://github.com/users/Xander-Carroll/projects/1/views/1?pane=issue&itemId=74530748), but I might not get around to it for a while.

**Comment by ian-aus** [comment]
Thanks very much, it works perfectly!
