### ISSUE TITLE
3d6 and 4d6 do not keep highest

### ISSUE THREAD

**Issue by Katiemp013** [Xander-Carroll/xanders-swnr-sheet#5]
When rolling 3d6 or 4d6 the system does not auto keep the highest 2. In the image attached I screenshot what the base sheet does in yellow and what your sheet does in purple :) 
![image](https://github.com/user-attachments/assets/96e3ce8e-4b6b-46c2-a261-3a6a0d311242)

**Comment by Xander-Carroll** [comment]
My bad! I didn't realize that rolling skill checks worked this way. The issue was fixed in [v1.1.2](https://github.com/Xander-Carroll/xanders-swnr-sheet/releases/tag/v1.1.2).

Thank you for the amount of detail you gave in your report, it made it very easy to find and fix the issue.
